openapi: 3.0.2
info:
  title: API Shopping Cart
  description: |-
    API responsável por praticamente todas as funcionalidades de gerenciamento:
    - Product
    - ProductCategory
    - User
    - ShoppingCart

    Links Importantes:
    - [Github](https://github.com/alessandrofeitoza/api-shopping-cart)

  license:
    name: GPLv3
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api
tags:
  - name: ProductCategory
    description: Endpoints relacionados as categorias dos produtos
  - name: User
    description: Endpoints relacionados aos usuários
paths:
  /product-categories:
    $ref: './components/paths/product-category/Collection.yaml'
  /product-categories/{id}:
    $ref: './components/paths/product-category/Item.yaml'
  /products:
    $ref: './components/paths/product/Collection.yaml'
  /products/{id}:
    $ref: './components/paths/product/Item.yaml'
  /users:
    $ref: './components/paths/user/Collection.yaml'
  /users/{id}:
    $ref: './components/paths/user/Item.yaml'
  /users/{user}/cart-items:
    $ref: './components/paths/cart-item/Collection.yaml'
  /users/{user}/cart-items/{id}:
    $ref: './components/paths/cart-item/Item.yaml'
components:
  schemas:
    Product:
      $ref: './components/schemas/Product.yaml'
    ProductCategory:
      $ref: './components/schemas/ProductCategory.yaml'
    ShoppingCartItem:
      $ref: './components/schemas/ShoppingCartItem.yaml'
    User:
      $ref: './components/schemas/User.yaml'
